name: ibm_watson_assistant
description: Pure dart package simplifying integration with IBM Watson Assistant v2 API.
version: 1.2.0
homepage: https://github.com/AlexHartford/ibm_watson_assistant

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  pedantic: ^1.11.0
