name: ibm_watson_assistant
description: Pure dart package simplifying integration with IBM Watson Assistant v2 API.
version: 1.0.0
homepage: https://github.com/AlexHartford/ibm_watson_assistant

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  meta: ^1.2.2